version: '3.4'

services:
  x21128863bdproject:
    image: x21128863bdproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
